# Generated by Django 4.0.1 on 2022-02-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['category', 'spanish']},
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
